class Language:
    def __init__(self, identifier, display_name, extension, editor_id, starter_code, keywords, builtins, std_libs, snippets, common_errors, ai_context):
        self.identifier = identifier
        self.display_name = display_name
        self.extension = extension
        self.editor_id = editor_id
        self.starter_code = starter_code
        self.keywords = keywords
        self.builtins = builtins
        self.std_libs = std_libs
        self.snippets = snippets
        self.common_errors = common_errors
        self.ai_context = ai_context


PYTHON_SNIPPETS = {
    "def": "def ${1:function_name}(${2:parameters}):\n    ${0:pass}",
    "for": "for ${1:item} in ${2:collection}:\n    ${0:pass}",
    "if": "if ${1:condition}:\n    ${0:pass}",
    "class": "class ${1:ClassName}:\n    ${0:pass}",
    "import": "import ${1:module}",
    "print": "print(${1:value})",
    "try": "try:\n    ${0:pass}\nexcept ${1:Exception} as e:\n    print(e)",
    "while": "while ${1:condition}:\n    ${0:pass}",
    "lambda": "lambda ${1:args}: ${0:expr}",
}

JAVASCRIPT_SNIPPETS = {
    "function": "function ${1:functionName}(${2:parameters}) {\n    ${0}\n}",
    "arrow": "const ${1:name} = (${2:params}) => {\n    ${0}\n};",
    "if": "if (${1:condition}) {\n    ${0}\n}",
    "for": "for (let ${1:i} = 0; ${1:i} < ${2:length}; ${1:i}++) {\n    ${0}\n}",
    "class": "class ${1:ClassName} {\n    constructor(${2:params}) {\n        ${0}\n    }\n}",
    "console": "console.log(${1:value});",
    "import": "import ${1:name} from '${2:module}';",
    "export": "export default ${1:name};",
    "try": "try {\n    ${0}\n} catch (${1:error}) {\n    console.error(${1:error});\n}",
}

CPP_SNIPPETS = {
    "main": "#include <iostream>\n\nint main() {\n    ${0}\n    return 0;\n}",
    "for": "for (int ${1:i} = 0; ${1:i} < ${2:n}; ${1:i}++) {\n    ${0}\n}",
    "if": "if (${1:condition}) {\n    ${0}\n}",
    "class": "class ${1:ClassName} {\npublic:\n    ${0}\n};",
    "include": "#include <${1:iostream}>",
    "using": "using namespace std;",
}

JAVA_SNIPPETS = {
    "main": "public static void main(String[] args) {\n    ${0}\n}",
    "class": "public class ${1:ClassName} {\n    ${0}\n}",
    "for": "for (int ${1:i} = 0; ${1:i} < ${2:n}; ${1:i}++) {\n    ${0}\n}",
    "if": "if (${1:condition}) {\n    ${0}\n}",
    "try": "try {\n    ${0}\n} catch (${1:Exception} e) {\n    e.printStackTrace();\n}",
    "sout": "System.out.println(${1:value});",
}

RUST_SNIPPETS = {
    "fn": "fn ${1:name}(${2:params}) -> ${3:type} {\n    ${0}\n}",
    "main": "fn main() {\n    ${0}\n}",
    "let": "let ${1:name} = ${0:value};",
    "for": "for ${1:item} in ${2:iterable} {\n    ${0}\n}",
    "if": "if ${1:condition} {\n    ${0}\n}",
    "match": "match ${1:value} {\n    ${2:pattern} => ${0},\n}",
    "println": "println!(\"${1:}\", ${0});",
}

GO_SNIPPETS = {
    "func": "func ${1:name}(${2:params}) ${3:type} {\n    ${0}\n}",
    "main": "package main\n\nfunc main() {\n    ${0}\n}",
    "if": "if ${1:condition} {\n    ${0}\n}",
    "for": "for ${1:i} := 0; ${1:i} < ${2:n}; ${1:i}++ {\n    ${0}\n}",
    "fmt": "fmt.Println(${1:value})",
    "import": "import \"${1:fmt}\"",
}

LANGUAGES = {
    "python": Language(
        identifier="python",
        display_name="Python",
        extension=".py",
        editor_id="python",
        starter_code="# Welcome to Nano AI Compiler\n# Write Python code here\n\nprint(\"Hello, World!\")",
        keywords=["False", "None", "True", "and", "as", "assert", "async", "await", "break", "class",
                   "continue", "def", "del", "elif", "else", "except", "finally", "for", "from", "global",
                   "if", "import", "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise",
                   "return", "try", "while", "with", "yield"],
        builtins=["print", "len", "str", "int", "float", "list", "dict", "set", "tuple", "range",
                   "map", "filter", "zip", "enumerate", "sorted", "reversed", "open", "input",
                   "type", "isinstance", "hasattr", "getattr", "setattr", "abs", "max", "min",
                   "sum", "any", "all", "round", "pow", "hex", "bin", "oct", "chr", "ord",
                   "repr", "str", "bool", "int", "float", "complex", "bytes", "bytearray",
                   "memoryview", "classmethod", "staticmethod", "property", "super", "object",
                   "Exception", "ValueError", "TypeError", "KeyError", "IndexError", "AttributeError",
                   "ImportError", "FileNotFoundError", "ZeroDivisionError"],
        std_libs=["os", "sys", "json", "math", "random", "datetime", "re", "collections",
                   "itertools", "functools", "pathlib", "subprocess", "shutil", "glob", "hashlib",
                   "base64", "uuid", "copy", "typing", "dataclasses", "enum", "string", "textwrap",
                   "pprint", "statistics", "decimal", "fractions", "time", "calendar", "io"],
        snippets=PYTHON_SNIPPETS,
        common_errors=["IndentationError", "SyntaxError", "NameError", "TypeError", "ValueError",
                        "KeyError", "IndexError", "AttributeError", "ImportError", "ZeroDivisionError"],
        ai_context="Python is dynamically typed. Uses indentation for scope. Print output with print()."
    ),
    "c": Language(
        identifier="c",
        display_name="C",
        extension=".c",
        editor_id="c",
        starter_code="#include <stdio.h>\n\nint main() {\n    printf(\"Hello, World!\\n\");\n    return 0;\n}",
        keywords=["auto", "break", "case", "char", "const", "continue", "default", "do", "double",
                   "else", "enum", "extern", "float", "for", "goto", "if", "int", "long", "register",
                   "return", "short", "signed", "sizeof", "static", "struct", "switch", "typedef",
                   "union", "unsigned", "void", "volatile", "while"],
        builtins=["printf", "scanf", "fprintf", "fscanf", "sprintf", "sscanf", "fopen", "fclose",
                   "fread", "fwrite", "fgets", "fputs", "fprintf", "fscanf", "malloc", "calloc",
                   "realloc", "free", "memcpy", "memset", "strlen", "strcmp", "strcpy", "strcat",
                   "strstr", "atoi", "atof", "rand", "srand", "exit", "abs"],
        std_libs=["stdio.h", "stdlib.h", "string.h", "math.h", "time.h", "ctype.h", "stdbool.h",
                   "stdint.h", "limits.h", "float.h", "errno.h", "assert.h"],
        snippets={},
        common_errors=["Segmentation fault", "Undefined reference", "Expected ';'", "Dangling pointer",
                        "Buffer overflow", "Memory leak", "Incompatible types"],
        ai_context="C is statically typed. Compiled language. Uses printf for output. Must include headers."
    ),
    "cpp": Language(
        identifier="cpp",
        display_name="C++",
        extension=".cpp",
        editor_id="cpp",
        starter_code="#include <iostream>\nusing namespace std;\n\nint main() {\n    cout << \"Hello, World!\" << endl;\n    return 0;\n}",
        keywords=["alignas", "alignof", "auto", "bool", "break", "case", "catch", "char", "class",
                   "const", "constexpr", "continue", "decltype", "default", "delete", "do", "double",
                   "else", "enum", "explicit", "export", "extern", "false", "float", "for", "friend",
                   "goto", "if", "inline", "int", "long", "mutable", "namespace", "new", "noexcept",
                   "nullptr", "operator", "override", "private", "protected", "public", "register",
                   "return", "short", "signed", "sizeof", "static", "struct", "switch", "template",
                   "this", "throw", "true", "try", "typedef", "typeid", "typename", "union",
                   "unsigned", "using", "virtual", "void", "volatile", "while"],
        builtins=["cout", "cin", "cerr", "clog", "endl", "printf", "scanf", "fopen", "fclose",
                   "malloc", "calloc", "realloc", "free", "memcpy", "memset", "strlen", "strcmp",
                   "strcpy", "strcat", "string", "vector", "map", "set", "list", "queue", "stack",
                   "sort", "find", "swap", "reverse", "make_pair", "pair", "unique_ptr", "shared_ptr"],
        std_libs=["iostream", "string", "vector", "map", "set", "algorithm", "cmath", "ctime",
                   "fstream", "sstream", "memory", "utility", "iterator", "numeric", "random",
                   "chrono", "thread", "mutex", "functional", "regex"],
        snippets=CPP_SNIPPETS,
        common_errors=["Segmentation fault", "Undefined reference", "No matching function",
                        "Expected ';'", "Dangling reference", "Memory leak", "Template compilation error"],
        ai_context="C++ is statically typed. Object-oriented. Uses cout for output. Supports classes and templates."
    ),
    "java": Language(
        identifier="java",
        display_name="Java",
        extension=".java",
        editor_id="java",
        starter_code="public class Main {\n    public static void main(String[] args) {\n        System.out.println(\"Hello, World!\");\n    }\n}",
        keywords=["abstract", "assert", "boolean", "break", "byte", "case", "catch", "char", "class",
                   "const", "continue", "default", "do", "double", "else", "enum", "extends", "final",
                   "finally", "float", "for", "goto", "if", "implements", "import", "instanceof",
                   "int", "interface", "long", "native", "new", "package", "private", "protected",
                   "public", "return", "short", "static", "strictfp", "super", "switch", "synchronized",
                   "this", "throw", "throws", "transient", "try", "void", "volatile", "while"],
        builtins=["System.out.println", "System.out.print", "System.out.printf", "String", "Integer",
                   "Double", "Boolean", "Character", "Long", "Float", "Short", "Byte", "Math",
                   "Arrays", "List", "ArrayList", "Map", "HashMap", "Set", "HashSet", "StringBuilder",
                   "StringBuffer", "Scanner", "BufferedReader", "File", "FileReader", "FileWriter",
                   "Exception", "RuntimeException", "IOException", "NullPointerException",
                   "ArrayIndexOutOfBoundsException", "ArithmeticException"],
        std_libs=["java.lang", "java.util", "java.io", "java.math", "java.net", "java.nio",
                   "java.time", "java.text", "java.security", "java.sql", "java.awt", "javax.swing"],
        snippets=JAVA_SNIPPETS,
        common_errors=["NullPointerException", "ArrayIndexOutOfBoundsException", "ClassNotFoundException",
                        "IOException", "ArithmeticException", "IllegalArgumentException",
                        "ConcurrentModificationException"],
        ai_context="Java is statically typed, object-oriented. Runs on JVM. Uses System.out.println for output."
    ),
    "javascript": Language(
        identifier="javascript",
        display_name="JavaScript",
        extension=".js",
        editor_id="javascript",
        starter_code="// Welcome to Nano AI Compiler\n// Write JavaScript code here\n\nconsole.log(\"Hello, World!\");",
        keywords=["break", "case", "catch", "class", "const", "continue", "debugger", "default",
                   "delete", "do", "else", "export", "extends", "false", "finally", "for", "function",
                   "if", "import", "in", "instanceof", "let", "new", "null", "of", "return", "super",
                   "switch", "this", "throw", "true", "try", "typeof", "var", "void", "while", "with", "yield"],
        builtins=["console.log", "console.error", "console.warn", "console.dir", "console.table",
                   "setTimeout", "setInterval", "clearTimeout", "clearInterval", "fetch",
                   "JSON.parse", "JSON.stringify", "parseInt", "parseFloat", "isNaN", "isFinite",
                   "encodeURI", "decodeURI", "encodeURIComponent", "decodeURIComponent",
                   "Math", "Date", "RegExp", "Map", "Set", "WeakMap", "WeakSet", "Promise",
                   "Array", "Object", "String", "Number", "Boolean", "Symbol", "Error",
                   "TypeError", "ReferenceError", "RangeError", "SyntaxError"],
        std_libs=["fs", "path", "http", "https", "url", "querystring", "crypto", "os",
                   "events", "stream", "buffer", "util", "assert", "timers", "child_process"],
        snippets=JAVASCRIPT_SNIPPETS,
        common_errors=["ReferenceError", "TypeError", "SyntaxError", "RangeError", "URIError",
                        "Uncaught TypeError: Cannot read property", "NaN", "undefined is not a function"],
        ai_context="JavaScript is dynamically typed. Prototype-based. Uses console.log for output. Supports async/await."
    ),
    "typescript": Language(
        identifier="typescript",
        display_name="TypeScript",
        extension=".ts",
        editor_id="typescript",
        starter_code="// Welcome to Nano AI Compiler\n// Write TypeScript code here\n\nconst greet = (name: string): void => {\n    console.log(`Hello, ${name}!`);\n};\n\ngreet(\"World\");",
        keywords=["abstract", "any", "as", "asserts", "async", "await", "boolean", "break", "case",
                   "catch", "class", "const", "continue", "debugger", "declare", "default", "delete",
                   "do", "else", "enum", "export", "extends", "false", "finally", "for", "from",
                   "function", "get", "if", "implements", "import", "in", "infer", "instanceof",
                   "interface", "is", "keyof", "let", "module", "namespace", "never", "new",
                   "null", "number", "of", "partial", "private", "protected", "public", "readonly",
                   "record", "return", "required", "set", "static", "string", "super", "switch",
                   "symbol", "this", "throw", "true", "try", "type", "typeof", "undefined",
                   "unique", "unknown", "var", "void", "while", "with", "yield"],
        builtins=["console.log", "console.error", "JSON.parse", "JSON.stringify", "parseInt",
                   "parseFloat", "Math", "Date", "RegExp", "Map", "Set", "Promise", "Array",
                   "Object", "String", "Number", "Boolean", "Error"],
        std_libs=["fs", "path", "http", "https", "url", "crypto", "os", "events", "stream",
                   "buffer", "util", "assert", "timers"],
        snippets={},
        common_errors=["Type 'undefined' is not assignable", "Property does not exist on type",
                        "Cannot find module", "Argument of type is not assignable",
                        "Object is possibly 'null'", "Object is possibly 'undefined'"],
        ai_context="TypeScript is a typed superset of JavaScript. Compiles to JavaScript. Uses console.log for output."
    ),
    "go": Language(
        identifier="go",
        display_name="Go",
        extension=".go",
        editor_id="go",
        starter_code="package main\n\nimport \"fmt\"\n\nfunc main() {\n    fmt.Println(\"Hello, World!\")\n}",
        keywords=["break", "case", "chan", "const", "continue", "default", "defer", "else",
                   "fallthrough", "for", "func", "go", "goto", "if", "import", "interface", "map",
                   "package", "range", "return", "select", "struct", "switch", "type", "var"],
        builtins=["fmt.Println", "fmt.Printf", "fmt.Sprintf", "fmt.Sprint", "len", "cap", "make",
                   "new", "append", "copy", "delete", "close", "panic", "recover", "error",
                   "string", "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16",
                   "uint32", "uint64", "float32", "float64", "bool", "byte", "rune", "complex64",
                   "complex128", "true", "false", "nil", "iota"],
        std_libs=["fmt", "os", "io", "net", "http", "json", "time", "strings", "strconv",
                   "sort", "math", "sync", "encoding", "errors", "log", "flag", "regexp",
                   "path", "filepath", "bufio", "bytes", "context"],
        snippets=GO_SNIPPETS,
        common_errors=["unused variable", "unused import", "cannot use type", "undefined",
                        "declared and not used", "no new variables on left side of :=",
                        "multiple-value in single-value context"],
        ai_context="Go is statically typed, compiled. Uses fmt.Println for output. Has built-in concurrency."
    ),
    "rust": Language(
        identifier="rust",
        display_name="Rust",
        extension=".rs",
        editor_id="rust",
        starter_code="fn main() {\n    println!(\"Hello, World!\");\n}",
        keywords=["as", "async", "await", "break", "const", "continue", "crate", "dyn", "else",
                   "enum", "extern", "false", "fn", "for", "if", "impl", "in", "let", "loop",
                   "match", "mod", "move", "mut", "pub", "ref", "return", "self", "Self",
                   "static", "struct", "super", "trait", "true", "type", "union", "unsafe",
                   "use", "where", "while"],
        builtins=["println!", "print!", "format!", "eprintln!", "eprint!", "write!", "writeln!",
                   "vec!", "String", "Vec", "HashMap", "HashSet", "Option", "Result", "Box",
                   "Rc", "Arc", "Cell", "RefCell", "Mutex", "RwLock", "Iterator", "Clone",
                   "Copy", "Debug", "Display", "PartialEq", "Eq", "PartialOrd", "Ord", "Hash",
                   "Default", "From", "Into", "AsRef", "AsMut", "Deref", "Drop"],
        std_libs=["std", "std::fs", "std::io", "std::net", "std::path", "std::collections",
                   "std::sync", "std::thread", "std::time", "std::env", "std::process",
                   "std::fmt", "std::str", "std::string", "std::vec", "std::boxed"],
        snippets=RUST_SNIPPETS,
        common_errors=["borrow of moved value", "cannot borrow as mutable", "expected ';'",
                        "unresolved import", "mismatched types", "use of undeclared type",
                        "lifetime mismatch", "type annotations needed"],
        ai_context="Rust is statically typed, compiled. Memory safe without GC. Uses println! for output."
    ),
    "php": Language(
        identifier="php",
        display_name="PHP",
        extension=".php",
        editor_id="php",
        starter_code="<?php\n\necho \"Hello, World!\\n\";\n?>",
        keywords=["__halt_compiler", "abstract", "and", "array", "as", "break", "callable",
                   "case", "catch", "class", "clone", "const", "continue", "declare", "default",
                   "die", "do", "echo", "else", "elseif", "empty", "enddeclare", "endfor",
                   "endforeach", "endif", "endswitch", "endwhile", "eval", "exit", "extends",
                   "final", "finally", "fn", "for", "foreach", "function", "global", "goto",
                   "if", "implements", "include", "include_once", "instanceof", "insteadof",
                   "interface", "isset", "list", "match", "namespace", "new", "or", "print",
                   "private", "protected", "public", "readonly", "require", "require_once",
                   "return", "static", "switch", "throw", "trait", "try", "unset", "use",
                   "var", "while", "xor", "yield"],
        builtins=["echo", "print", "var_dump", "print_r", "strlen", "strpos", "str_replace",
                   "substr", "trim", "explode", "implode", "json_encode", "json_decode",
                   "array_merge", "array_keys", "array_values", "count", "sort", "in_array",
                   "isset", "empty", "unset", "is_array", "is_string", "is_int", "is_float",
                   "is_null", "gettype", "settype", "strtolower", "strtoupper", "ucfirst",
                   "number_format", "date", "time", "strtotime", "file_get_contents",
                   "file_put_contents", "fopen", "fwrite", "fclose", "mysqli_connect",
                   "PDO", "Exception", "Error", "InvalidArgumentException"],
        std_libs=["standard", "json", "session", "PDO", "mysqli", "curl", "mbstring",
                   "filter", "hash", "openssl", "fileinfo", "ctype", "date", "spl"],
        snippets={},
        common_errors=["Parse error: syntax error", "Fatal error: Uncaught Error",
                        "Notice: Undefined variable", "Warning: array_merge",
                        "Fatal error: Allowed memory size exhausted",
                        "Warning: include(): Failed opening"],
        ai_context="PHP is server-side scripting language. Uses echo for output. Variables start with $."
    ),
    "ruby": Language(
        identifier="ruby",
        display_name="Ruby",
        extension=".rb",
        editor_id="ruby",
        starter_code='# Welcome to Nano AI Compiler\n# Write Ruby code here\n\nputs "Hello, World!"',
        keywords=["BEGIN", "END", "alias", "and", "begin", "break", "case", "class", "def",
                   "defined?", "do", "else", "elsif", "end", "ensure", "false", "for", "if",
                   "in", "module", "next", "nil", "not", "or", "redo", "rescue", "retry",
                   "return", "self", "super", "then", "true", "undef", "unless", "until",
                   "when", "while", "yield", "__ENCODING__", "__LINE__", "__FILE__"],
        builtins=["puts", "print", "p", "gets", "chomp", "to_s", "to_i", "to_f", "to_a",
                   "to_h", "Array", "Hash", "String", "Integer", "Float", "Symbol", "Range",
                   "Enumerable", "each", "map", "select", "reject", "reduce", "inject",
                   "sort", "uniq", "flatten", "compact", "merge", "keys", "values",
                   "include?", "empty?", "nil?", "respond_to?", "send", "define_method",
                   "attr_accessor", "attr_reader", "attr_writer", "raise", "begin", "rescue",
                   "ensure", "new", "initialize", "inspect", "to_s"],
        std_libs=["json", "yaml", "fileutils", "pathname", "date", "time", "digest",
                   "base64", "erb", "csv", "rexml", "net/http", "uri", "openssl",
                   "socket", "thread", "mutex", "monitor", "set", "struct", "ostruct"],
        snippets={},
        common_errors=["undefined method", "undefined local variable", "syntax error",
                        "NoMethodError", "NameError", "ArgumentError", "TypeError",
                        "ZeroDivisionError", "RuntimeError", "LoadError"],
        ai_context="Ruby is dynamically typed. Object-oriented. Uses puts for output. Everything is an object."
    ),
    "kotlin": Language(
        identifier="kotlin",
        display_name="Kotlin",
        extension=".kt",
        editor_id="kotlin",
        starter_code="fun main() {\n    println(\"Hello, World!\")\n}",
        keywords=["abstract", "actual", "annotation", "as", "as?", "break", "by", "catch",
                   "class", "companion", "const", "constructor", "continue", "crossinline",
                   "data", "delegate", "do", "dynamic", "else", "enum", "expect", "external",
                   "false", "field", "file", "final", "finally", "for", "fun", "if", "import",
                   "in", "infix", "init", "inline", "inner", "interface", "internal", "is",
                   "it", "lateinit", "noinline", "null", "object", "open", "operator",
                   "out", "override", "package", "param", "private", "property", "protected",
                   "public", "receiver", "reified", "return", "sealed", "setparam", "super",
                   "suspend", "tailrec", "this", "throw", "true", "try", "typealias",
                   "typeof", "val", "var", "vararg", "when", "where", "while"],
        builtins=["println", "print", "readln", "readLine", "listOf", "setOf", "mapOf",
                   "mutableListOf", "mutableSetOf", "mutableMapOf", "arrayOf", "intArrayOf",
                   "doubleArrayOf", "String", "Int", "Double", "Float", "Long", "Short",
                   "Byte", "Boolean", "Char", "Any", "Unit", "Nothing", "List", "Set",
                   "Map", "MutableList", "MutableSet", "MutableMap", "Pair", "Triple",
                   "Array", "IntArray", "DoubleArray", "Arraylist", "Hashmap", "Hashset",
                   "Sequence", "rangeTo", "downTo", "step", "until", "repeat", "with",
                   "apply", "also", "let", "run", "use", "takeIf", "takeUnless",
                   "check", "require", "assert", "error", "TODO"],
        std_libs=["kotlin.io", "kotlin.text", "kotlin.collections", "kotlin.ranges",
                   "kotlin.sequences", "kotlin.comparisons", "kotlin.math",
                   "java.io", "java.util", "java.lang"],
        snippets={},
        common_errors=["Unresolved reference", "Type mismatch", "Nullable must be handled",
                        "Variable must be initialized", "Expression 'when' is not exhaustive",
                        "Cannot infer type", "Only safe (?.) or non-null asserted (!!.) calls"],
        ai_context="Kotlin is statically typed. JVM language. Uses println for output. Null-safe by design."
    ),
    "swift": Language(
        identifier="swift",
        display_name="Swift",
        extension=".swift",
        editor_id="swift",
        starter_code='import Foundation\n\nprint("Hello, World!")',
        keywords=["associatedtype", "async", "await", "as", "break", "case", "catch", "class",
                   "continue", "default", "defer", "deinit", "didSet", "do", "dynamic",
                   "else", "enum", "extension", "fallthrough", "false", "fileprivate",
                   "for", "func", "get", "guard", "if", "import", "in", "indirect",
                   "infix", "init", "inout", "internal", "is", "lazy", "let", "mutating",
                   "nonmutating", "open", "operator", "optional", "override", "package",
                   "postfix", "precedence", "prefix", "private", "protocol", "public",
                   "repeat", "required", "rethrows", "return", "self", "Self", "set",
                   "some", "static", "struct", "subscript", "super", "switch", "throw",
                   "throws", "true", "try", "typealias", "unowned", "var", "weak",
                   "where", "while", "willSet"],
        builtins=["print", "debugPrint", "dump", "fatalError", "precondition", "assert",
                   "String", "Int", "Double", "Float", "Bool", "Character", "Array",
                   "Dictionary", "Set", "Optional", "Substring", "ClosedRange", "Range",
                   "ArraySlice", "Data", "URL", "Date", "Data", "Error", "Result",
                   "Codable", "Encodable", "Decodable", "Equatable", "Hashable",
                   "Comparable", "Identifiable", "CustomStringConvertible",
                   "Sequence", "Collection", "IteratorProtocol", "map", "filter",
                   "reduce", "compactMap", "flatMap", "sorted", "forEach", "contains"],
        std_libs=["Foundation", "UIKit", "SwiftUI", "Combine", "Dispatch", "CoreData",
                   "CloudKit", "Network", "Security", "CryptoKit", "NaturalLanguage",
                   "AVFoundation", "CoreGraphics", "CoreImage", "Metal"],
        snippets={},
        common_errors=["Unexpectedly found nil", "Type 'Any' has no member",
                        "Cannot convert value of type", "Argument must be a constant",
                        "Value of optional type not unwrapped", "Missing return in function",
                        "Cannot assign to property: function call returns immutable value"],
        ai_context="Swift is statically typed, compiled. Uses print for output. Optional-safe with ? and !."
    ),
    "cs": Language(
        identifier="cs",
        display_name="C#",
        extension=".cs",
        editor_id="csharp",
        starter_code='using System;\n\nclass Program {\n    static void Main() {\n        Console.WriteLine("Hello, World!");\n    }\n}',
        keywords=["abstract", "as", "async", "await", "base", "bool", "break", "byte", "case",
                   "catch", "char", "checked", "class", "const", "continue", "decimal", "default",
                   "delegate", "do", "double", "else", "enum", "event", "explicit", "extern",
                   "false", "finally", "fixed", "float", "for", "foreach", "goto", "if",
                   "implicit", "in", "int", "interface", "internal", "is", "lock", "long",
                   "namespace", "new", "null", "object", "operator", "out", "override",
                   "params", "private", "protected", "public", "readonly", "ref", "return",
                   "sbyte", "sealed", "short", "sizeof", "stackalloc", "static", "string",
                   "struct", "switch", "this", "throw", "true", "try", "typeof", "uint",
                   "ulong", "unchecked", "unsafe", "ushort", "using", "var", "virtual",
                   "void", "volatile", "while"],
        builtins=["Console.WriteLine", "Console.Write", "Console.ReadLine", "Console.Read",
                   "Convert.ToInt32", "Convert.ToString", "Int32.Parse", "String.Format",
                   "String.Join", "String.Split", "String.IsNullOrEmpty",
                   "String.IsNullOrWhiteSpace", "Math", "Random", "DateTime", "TimeSpan",
                   "Guid", "Uri", "StringBuilder", "Array", "List", "Dictionary",
                   "HashSet", "Queue", "Stack", "SortedList", "IEnumerable",
                   "IEnumerator", "IDisposable", "IComparable", "IEquatable",
                   "Task", "Task<T>", "Func", "Action", "Predicate", "Tuple",
                   "ValueTuple", "Nullable", "Exception", "InvalidOperationException",
                   "ArgumentNullException", "ArgumentException", "IndexOutOfRangeException"],
        std_libs=["System", "System.IO", "System.Net", "System.Text", "System.Threading",
                   "System.Threading.Tasks", "System.Collections", "System.Collections.Generic",
                   "System.Linq", "System.Data", "System.Xml", "System.Web",
                   "System.Security", "System.Diagnostics", "System.Reflection"],
        snippets={},
        common_errors=["NullReferenceException", "IndexOutOfRangeException",
                        "InvalidOperationException", "ArgumentNullException",
                        "FormatException", "DivideByZeroException",
                        "Object reference not set to an instance of an object",
                        "Cannot implicitly convert type"],
        ai_context="C# is statically typed, object-oriented. Uses Console.WriteLine for output. Runs on .NET."
    ),
    "bash": Language(
        identifier="bash",
        display_name="Bash",
        extension=".sh",
        editor_id="shell",
        starter_code='#!/bin/bash\n\necho "Hello, World!"',
        keywords=["if", "then", "else", "elif", "fi", "for", "while", "until", "do", "done",
                   "case", "esac", "function", "return", "local", "export", "readonly",
                   "declare", "typeset", "select", "in", "not", "and", "or"],
        builtins=["echo", "printf", "read", "cd", "pwd", "ls", "mkdir", "rmdir", "rm",
                   "cp", "mv", "cat", "grep", "sed", "awk", "cut", "sort", "uniq",
                   "wc", "find", "xargs", "test", "let", "expr", "source", "alias",
                   "unalias", "type", "which", "exit", "trap", "kill", "jobs", "bg",
                   "fg", "wait", "sleep", "shift", "getopts", "eval", "exec", "ulimit",
                   "umask", "basename", "dirname", "readlink", "date", "head", "tail"],
        std_libs=["coreutils", "bash builtins", "GNU tools"],
        snippets={},
        common_errors=["command not found", "No such file or directory",
                        "Permission denied", "syntax error near unexpected token",
                        "unary operator expected", "binary operator expected",
                        "division by zero", "unbound variable"],
        ai_context="Bash is a Unix shell and command language. Uses echo for output. Commands are shell builtins and GNU tools."
    ),
    "sql": Language(
        identifier="sql",
        display_name="SQL",
        extension=".sql",
        editor_id="sql",
        starter_code="-- Write SQL queries here\n\nSELECT 'Hello, World!' AS greeting;",
        keywords=["SELECT", "FROM", "WHERE", "INSERT", "UPDATE", "DELETE", "CREATE", "ALTER",
                   "DROP", "TABLE", "INDEX", "VIEW", "JOIN", "INNER", "LEFT", "RIGHT",
                   "OUTER", "CROSS", "ON", "AND", "OR", "NOT", "IN", "BETWEEN", "LIKE",
                   "IS", "NULL", "AS", "DISTINCT", "ORDER", "BY", "GROUP", "HAVING",
                   "LIMIT", "OFFSET", "UNION", "ALL", "EXISTS", "CASE", "WHEN", "THEN",
                   "ELSE", "END", "BEGIN", "COMMIT", "ROLLBACK", "GRANT", "REVOKE",
                   "PRIMARY", "KEY", "FOREIGN", "REFERENCES", "CONSTRAINT", "DEFAULT",
                   "CHECK", "UNIQUE", "AUTO_INCREMENT", "SERIAL", "INT", "VARCHAR",
                   "TEXT", "BOOLEAN", "DATE", "TIMESTAMP", "FLOAT", "DOUBLE", "DECIMAL",
                   "COUNT", "SUM", "AVG", "MIN", "MAX", "COALESCE", "NULLIF", "CAST"],
        builtins=["COUNT", "SUM", "AVG", "MIN", "MAX", "COALESCE", "NULLIF", "CAST",
                   "CONVERT", "UPPER", "LOWER", "TRIM", "LENGTH", "SUBSTRING",
                   "REPLACE", "CONCAT", "NOW", "CURDATE", "CURTIME", "DATE_FORMAT",
                   "EXTRACT", "YEAR", "MONTH", "DAY", "HOUR", "MINUTE", "SECOND",
                   "GROUP_CONCAT", "DISTINCT", "IF", "IFNULL"],
        std_libs=["SQL Standard", "MySQL", "PostgreSQL", "SQLite"],
        snippets={},
        common_errors=["Syntax error", "Table doesn't exist", "Column doesn't exist",
                        "Duplicate entry", "Foreign key constraint fails",
                        "Cannot add or update a child row", "Data too long for column",
                        "Division by zero", "Unknown column"],
        ai_context="SQL is a domain-specific language for managing relational databases. Uses SELECT for queries."
    ),
    "html": Language(
        identifier="html",
        display_name="HTML",
        extension=".html",
        editor_id="html",
        starter_code="<!DOCTYPE html>\n<html>\n<head>\n    <title>Nano AI Compiler</title>\n</head>\n<body>\n    <h1>Hello, World!</h1>\n</body>\n</html>",
        keywords=["html", "head", "body", "div", "span", "p", "a", "img", "ul", "ol", "li",
                   "table", "tr", "td", "th", "form", "input", "button", "select", "option",
                   "textarea", "h1", "h2", "h3", "h4", "h5", "h6", "header", "footer",
                   "nav", "main", "section", "article", "aside", "figure", "figcaption",
                   "video", "audio", "canvas", "svg", "style", "script", "link", "meta",
                   "title", "doctype", "br", "hr", "strong", "em", "b", "i", "u", "s",
                   "blockquote", "pre", "code", "label", "fieldset", "legend"],
        builtins=["document.getElementById", "document.querySelector",
                   "document.createElement", "document.body", "window",
                   "window.location", "window.alert", "window.confirm",
                   "window.prompt", "console.log", "fetch", "JSON.parse",
                   "JSON.stringify", "setTimeout", "setInterval",
                   "addEventListener", "removeEventListener", "Math", "Date",
                   "Array", "Object", "String", "Number"],
        std_libs=["DOM API", "Fetch API", "Canvas API", "Web APIs"],
        snippets={},
        common_errors=["Unexpected token", "Cannot read property of null",
                        "Undefined is not a function", "Failed to fetch",
                        "Unexpected end of input", "Invalid tag name",
                        "Duplicate attribute", "Unclosed tag"],
        ai_context="HTML is a markup language for web pages. Uses tags for structure. Can include CSS and JavaScript."
    ),
    "css": Language(
        identifier="css",
        display_name="CSS",
        extension=".css",
        editor_id="css",
        starter_code="/* Welcome to Nano AI Compiler */\n/* Write CSS code here */\n\nbody {\n    font-family: Arial, sans-serif;\n    margin: 0;\n    padding: 0;\n}\n\nh1 {\n    color: #333;\n}",
        keywords=["color", "background", "background-color", "font-size", "font-family",
                   "font-weight", "margin", "padding", "border", "display", "position",
                   "top", "right", "bottom", "left", "width", "height", "min-width",
                   "max-width", "min-height", "max-height", "overflow", "flex",
                   "grid", "align-items", "justify-content", "text-align", "vertical-align",
                   "float", "clear", "z-index", "opacity", "visibility", "transform",
                   "transition", "animation", "box-shadow", "text-shadow", "border-radius",
                   "outline", "cursor", "list-style", "text-decoration", "white-space",
                   "word-wrap", "word-break", "line-height", "letter-spacing",
                   "text-transform", "box-sizing", "flex-direction", "flex-wrap",
                   "flex-flow", "gap", "grid-template", "grid-column", "grid-row",
                   "align-self", "justify-self", "order", "media", "import", "keyframes",
                   "important", "initial", "inherit", "unset", "revert", "var"],
        builtins=["rgb", "rgba", "hsl", "hsla", "hex colors", "calc", "min", "max",
                   "clamp", "url", "attr", "counter", "counters", "env", "var"],
        std_libs=["CSS3", "CSS Grid", "Flexbox", "Animations"],
        snippets={},
        common_errors=["Unexpected token", "Property doesn't exist", "Invalid value",
                        "Expected expression", "Expected selector", "Invalid at-rule"],
        ai_context="CSS is a stylesheet language for styling HTML documents. Uses selectors and properties."
    ),
}


class LanguageManager:
    def __init__(self):
        self._languages = LANGUAGES

    def get_all(self):
        return [{
            "identifier": lang.identifier,
            "display_name": lang.display_name,
            "extension": lang.extension,
            "editor_id": lang.editor_id,
            "starter_code": lang.starter_code,
            "keywords": lang.keywords,
            "builtins": lang.builtins,
            "std_libs": lang.std_libs,
            "snippets": lang.snippets,
            "common_errors": lang.common_errors,
        } for lang in self._languages.values()]

    def get_language(self, identifier):
        return self._languages.get(identifier)

    def validate(self, identifier):
        return identifier in self._languages

    def get_starter_code(self, identifier):
        lang = self._languages.get(identifier)
        return lang.starter_code if lang else ""

    def get_extension(self, identifier):
        lang = self._languages.get(identifier)
        return lang.extension if lang else ".txt"

    def get_editor_id(self, identifier):
        lang = self._languages.get(identifier)
        return lang.editor_id if lang else "plaintext"

    def get_keywords(self, identifier):
        lang = self._languages.get(identifier)
        return lang.keywords if lang else []

    def get_builtins(self, identifier):
        lang = self._languages.get(identifier)
        return lang.builtins if lang else []

    def get_snippets(self, identifier):
        lang = self._languages.get(identifier)
        return lang.snippets if lang else {}

    def get_ai_context(self, identifier):
        lang = self._languages.get(identifier)
        return lang.ai_context if lang else ""


language_manager = LanguageManager()
